---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  install-pc-hooks:
    desc: "Install pre-commit hooks"
    cmds:
      - pre-commit install

  clear-cache:
    desc: "Clear pre-commit cache"
    cmds:
      - pre-commit clean

  run-hooks:
    desc: "Run all pre-commit hooks locally"
    cmds:
      - pre-commit run --all-files --show-diff-on-failure

  run-pre-commit:
    desc: "Update, clear cache, and run pre-commit hooks"
    deps:
      - install-pc-hooks
    cmds:
      - task: update-hooks
      - task: clear-cache
      - task: run-hooks

  update-hooks:
    desc: "Update pre-commit hooks"
    cmds:
      - pre-commit autoupdate
