---
  name: "Meta Sync labels"
  on:
    workflow_dispatch:
    push:
      branches: ["main"]
      paths: [".github/labels.yaml"]

  jobs:
    labels:
      name: Sync Labels
      runs-on: ubuntu-latest
      steps:
        - name: Generate PAT Token
          uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1.7
          id: generate-pat
          with:
            app_id: "${{ secrets.BOT_APP_ID }}"
            private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
            installation_id: "${{ secrets.BOT_INSTALLATION_ID }}"

        - name: Set up git repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
          with:
            token: "${{ steps.generate-pat.outputs.token }}"

        - name: Sync Labels
          uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
          with:
            config-file: .github/labels.yaml
            token: "${{ steps.generate-pat.outputs.token }}"
            delete-other-labels: true
