---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
includes:
  onepassword: ./onepassword/Taskfile.yaml
  local: ./local/Taskfile.yaml

tasks:
  default:
    desc: "List available secret management tasks"
    cmds:
      - |
        echo "Secret Management Tasks"
        echo "======================="
        echo "This Taskfile provides tools for managing secrets using either:"
        echo "  - Local encryption with SOPS and Age"
        echo "  - 1Password"
        echo ""
        echo "Available commands:"
        echo "  task local:<cmd>         - Local encryption commands with SOPS/Age"
        echo "    task local:create-age-keypair - Generate a new Age keypair"
        echo "    task local:encrypt-file      - Encrypt a file with SOPS/Age"
        echo "    task local:decrypt-file      - Decrypt a file with SOPS/Age"
        echo ""
        echo "  task onepassword:<cmd>   - 1Password commands"
        echo "    task onepassword:setup-account  - Set up 1Password CLI"
        echo "    task onepassword:create-vault   - Create a new 1Password vault"
        echo "    task onepassword:store-secret   - Store a secret in 1Password"
        echo "    task onepassword:get-secret     - Retrieve a secret from 1Password"
        echo "    task onepassword:encrypt-file   - Encrypt a file with 1Password"
        echo "    task onepassword:decrypt-file   - Decrypt a file from 1Password"
        echo "    task onepassword:delete-secret  - Delete a secret from 1Password"
        echo "    task onepassword:list-secrets   - List secrets in a vault"
        echo ""
        echo "For more details, run: task -l"
